### PR TITLE
Fix export for declaration files (TS)

### LINKED ISSUE #307: [v3] Cannot find module 'ember-load-initializers' or its corresponding type declarations.
After upgrade to v3 we see following error:

`Cannot find module 'ember-load-initializers' or its corresponding type declarations.`

I think we need to add ad extra hint to find declaration

### PR DESCRIPTION
**Pull request by mkszepp**
fix #307 & #309

### CODE REVIEW

**Comment by ef4** [comment]
Thanks!
