### ISSUE TITLE
[v3] Cannot find module 'ember-load-initializers' or its corresponding type declarations.

### ISSUE THREAD

**Issue by mkszepp** [ember-cli/ember-load-initializers#307]
After upgrade to v3 we see following error:

`Cannot find module 'ember-load-initializers' or its corresponding type declarations.`

I think we need to add ad extra hint to find declaration

**Comment by Turbo87** [comment]
I'm seeing a roughly similar error when running the crates.io test suite after the upgrade:

```
not ok 1 Chrome 129.0 - [undefined ms] - Global error: Uncaught Error: Could not find module `ember-load-initializers` imported from `(require)` at http://localhost:7357/assets/vendor.js, line 256
    ---
        browser log: |
            {"type":"error","text":"Uncaught Error: Could not find module `ember-load-initializers` imported from `(require)` at http://localhost:7357/assets/vendor.js, line 256\n","testContext":{}}
    ...
not ok 2 Chrome 129.0 - [undefined ms] - Global error: Uncaught Error: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/365540048851/tests/index.html?hidepassed&split=2&partition=2, line 100
    ---
        browser log: |
            {"type":"error","text":"Uncaught Error: The tests file was not loaded. Make sure your tests index.html includes \"assets/tests.js\". at http://localhost:7357/365540048851/tests/index.html?hidepassed&split=2&partition=2, line 100\n","testContext":{"state":"complete"}}
    ...
not ok 3 Chrome 129.0 - [undefined ms] - Global error: Uncaught Error: Could not find module `ember-load-initializers` imported from `(require)` at http://localhost:7357/assets/vendor.js, line 256
    ---
        browser log: |
            {"type":"error","text":"Uncaught Error: Could not find module `ember-load-initializers` imported from `(require)` at http://localhost:7357/assets/vendor.js, line 256\n","testContext":{}}
    ...
not ok 4 Chrome 129.0 - [undefined ms] - Global error: Uncaught Error: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/365539769301/tests/index.html?hidepassed&split=2&partition=1, line 100
    ---
        browser log: |
            {"type":"error","text":"Uncaught Error: The tests file was not loaded. Make sure your tests index.html includes \"assets/tests.js\". at http://localhost:7357/365539769301/tests/index.html?hidepassed&split=2&partition=1, line 100\n","testContext":{"state":"complete"}}
    ...
```

see https://github.com/rust-lang/crates.io/pull/9516

/cc @ef4

**Comment by mkszepp** [comment]
@Turbo87 added extra issue your reported error... https://github.com/ember-cli/ember-load-initializers/issues/309

**Comment by mkszepp** [comment]
ah its maybe fixed with same PR.. because classic build brings better error :)

`Module not found: Error: Invalid "exports" target "dist/index.js" defined for "." in the package config /tmp/broccoli-1851r09KjyAsYHsR/cache-150-webpack_bundler_ember_auto_import_webpack/node_modules/ember-load-initializers/package.json, targets must start with "./"`
